run:
  name: "scenario_C"
  disable_progressbar: true

foresight: "myopic"

scenario:
  simpl:
    - ""
  clusters:
    # - "45"
    - "20"
  ll:
    - "c1.1"
  opts:
    - ""
  sector_opts:
    - "1000SEG-T-H-B-I-A-Co2L0.5-EXPORT4-offwind"
  planning_horizons:
    - 2030

param_sweep_num_nets: 400
param_sweep:
  export_capital_cost:
    carrier: "H2 exports"
    attr: "c" # Capital cost
    factors: [0.8, 0.9, 1.0, 1.1, 1.2]
  export_marginal_cost:
    carrier: "H2 exports"
    attr: "m" # Marginal cost
    factors: [0.8, 0.9, 1.0, 1.1, 1.2]
  export_efficiency:
    carrier: "H2 exports"
    attr: "f" # Efficiency
    factors: [0.8, 0.9, 1.0, 1.1, 1.2]
  electrolysis_cost:
    carrier: "H2 Electrolysis"
    attr: "c" # Capital cost
    factors: [0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3]
  SMR_cost:
    carrier: "SMR CC"
    attr: "c" # Capital cost
    factors: [0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3]
  sequestration_cost:
    carrier: "co2 stored"
    attr: "c" # Capital cost: sequestration is modelled as store
    factors: [0.8, 0.9, 1.0, 1.1, 1.2]
  onwind_cost:
    carrier: "onwind"
    attr: "c" # Capital cost
    factors: [0.8, 0.9, 1.0, 1.1, 1.2]
  offwind-ac_cost:
    carrier: "offwindfixed"
    attr: "c" # Capital cost
    factors: [0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3]
  offwind-float_cost:
    carrier: "offwindfloat"
    attr: "c" # Capital cost
    factors: [0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3]


countries: ["NO", "SE", "FI", "NL", "DE", "DK", "GB"]

focus_weights:
  "NO": 0.69
  "SE": 0.2
  "FI": 0.1
  "NL": 0.0025
  "DE": 0.0025
  "DK": 0.0025
  "GB": 0.0025

electricity:
  # Only select powerplants phased out after 2022. Note that this is
  # only relevant for the initial network; for the 2030 planning
  # horizon network (at add_brownfield) powerplants that are
  # decommissioned by 2030 are removed anyway.
  powerplants_filter: (DateOut >= 2022 or DateOut != DateOut)

  estimate_renewable_capacities:
    year: 2022

atlite:
  cutouts:
    base:
      module: era5

sector:
  norwegian_hydrogen_exports: true
  gas_network: true
  H2_retrofit: false
  H2_network: false
  co2_spatial: false
  co2_sequestration_lifetime: .inf
  co2network: false
  SMR: false
  SMR_cc: false # Scenario C: NO SMR
  methanation: false
  dac: false
  ammonia: false
  fischer_tropsch: false
  biomass_spatial: true
  conventional_generation:
    OCGT: gas
    nuclear: uranium

existing_capacities:
  conventional_carriers:
    - lignite
    - coal
    - oil
    - uranium
    - gas

costs:
  year: 2030
  capital_cost:
    # From NVE, we have that floating offwind (excluding connection
    # costs) costs 46000 NOK / kWel in 2021 NOK.
    # With a conversion rate for 2021 of 0.0984, this is 4526 EUR_2021.
    # Using Eurostat HICP rates we find that inflation 2015-2021 was 8.82%,
    # Making for a cost of 4160 EUR_2015
    offwind-float: 4160

clustering:
  simplify_network:
    remove_stubs: ["GB", "DE", "NL", "DK", "SE", "FI"]

solving:
  solver_options:
    gurobi-default:
      threads: 1

compression:
  enable: true
  options:
    zlib: true
    complevel: 3
    least_significant_digit: 3

wind_bias_correction:
  corrector_year: 2013
  num_near_wind_parks: 10
  num_parallel_processes: 48

plotting:
  map:
    # Whole region:
    # boundaries: [0, 25, 45, 71]
    # Just Norway:
    boundaries: [0, 20, 57, 71]
  eu_node_location:
    x: 0.
    y: 60.
  tech_colors:
    H2 export: "#f081dc"
