run:
  name: "scenario_A"
  disable_progressbar: true

foresight: "myopic"

scenario:
  simpl:
    - ""
  clusters:
    # - "45"
    - "20"
  ll:
    - "c1.1"
  opts:
    - ""
  sector_opts:
    - "1000SEG-T-H-B-I-A-Co2L0.5-EXPORT4"
  planning_horizons:
    - 2030

param_sweep_num_nets: 200
param_sweep:
  export_capital_cost:
    carrier: "H2 exports"
    attr: "c" # Capital cost
    factors: [0.8, 1.0, 1.2]
  export_marginal_cost:
    carrier: "H2 exports"
    attr: "m" # Marginal cost
    factors: [0.8, 1.0, 1.2]
  electrolysis_cost:
    carrier: "H2 Electrolysis"
    attr: "c" # Capital cost
    factors: [0.8, 1.0, 1.2]
  SMR_cost:
    carrier: "SMR CC"
    attr: "c" # Capital cost
    factors: [0.8, 1.0, 1.2]
  sequestration_cost:
    carrier: "co2 stored"
    attr: "c" # Capital cost: sequestration is modelled as store
    factors: [0.8, 1.0, 1.2]
  onwind_cost:
    carrier: "onwind"
    attr: "c" # Capital cost
    factors: [0.8, 1.0, 1.2]
  offwind-ac_cost:
    carrier: "offwind-ac"
    attr: "c" # Capital cost
    factors: [0.8, 1.0, 1.2]
  offwind-dc_cost:
    carrier: "offwind-dc"
    attr: "c" # Capital cost
    factors: [0.8, 1.0, 1.2]
  offwind-float_cost:
    carrier: "offwind-float"
    attr: "c" # Capital cost
    factors: [0.8, 1.0, 1.2]


countries: ["NO", "SE", "NL", "DE", "DK", "GB"]

focus_weights:
  "NO": 0.69
  "SE": 0.3
  "NL": 0.0033
  "DE": 0.0033
  "DK": 0.0033

electricity:
  # Only select powerplants phased out after 2022. Note that this is
  # only relevant for the initial network; for the 2030 planning
  # horizon network (at add_brownfield) powerplants that are
  # decommissioned by 2030 are removed anyway.
  powerplants_filter: (DateOut >= 2022 or DateOut != DateOut)

  estimate_renewable_capacities:
    year: 2022

atlite:
  cutouts:
    base:
      module: era5

costs:
  year: 2030

sector:
  norwegian_hydrogen_exports: true
  gas_network: true
  H2_retrofit: false
  H2_network: false
  co2_spatial: false
  co2_sequestration_lifetime: .inf
  co2network: false
  SMR: false
  SMR_cc: true
  methanation: false
  dac: false
  ammonia: true
  fischer_tropsch: false
  biomass_spatial: true
  conventional_generation:
    OCGT: gas

existing_capacities:
  conventional_carriers:
    - lignite
    - coal
    - oil
    - uranium

clustering:
  simplify_network:
    algorithm: "hac"
    feature: "onwind-time"
  cluster_network:
    algorithm: "hac"
    feature: "onwind-time"

solving:
  solver_options:
    gurobi-default:
      threads: 1

plotting:
  map:
    # Whole region:
    boundaries: [0, 25, 45, 71]
    # Just Norway:
    # boundaries: [0, 20, 57, 71]
  eu_node_location:
    x: 0.
    y: 60.
  tech_colors:
    H2 export: "#f081dc"
